# Generated by Django 4.1 on 2022-09-03 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DBModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('price', models.IntegerField(default=0)),
                ('bedrooms', models.IntegerField(default=0)),
                ('bathrooms', models.FloatField(default=0)),
                ('sqft_living', models.IntegerField(default=0)),
                ('sqft_lot', models.IntegerField(default=0)),
                ('floors', models.FloatField(default=0)),
                ('waterfront', models.IntegerField(default=0)),
                ('view', models.IntegerField(default=0)),
                ('condition', models.IntegerField(default=0)),
                ('sqft_above', models.IntegerField(default=0)),
                ('sqft_basement', models.IntegerField(default=0)),
                ('yr_built', models.IntegerField(default=0)),
                ('yr_renovated', models.IntegerField(default=0)),
                ('street', models.CharField(max_length=150)),
            ],
        ),
    ]
