# Generated by Django 4.1 on 2022-09-03 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbmodel',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
