# Generated by Django 4.1 on 2022-09-03 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_dbmodel_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbmodel',
            name='date',
            field=models.DateField(),
        ),
    ]
